### ISSUE TITLE
Package IPA Failed

### ISSUE THREAD

**Issue by TanDing** [tuarua/Apple-Signin-ANE#10]
Mac 10.14
AirSDK 33.1

Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$__TtC8FreSwift14FreSwiftBridge", referenced from:
      objc-class-ref in com.tuarua.AppleSignInANE.o
  "_OBJC_CLASS_$__TtC17AppleSignInANE_FW15SwiftController", referenced from:
      objc-class-ref in com.tuarua.AppleSignInANE.o
ld: symbol(s) not found for architecture armv7
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC8FreSwift14FreSwiftBridge", referenced from:
      objc-class-ref in com.tuarua.AppleSignInANE.o
  "_OBJC_CLASS_$__TtC17AppleSignInANE_FW15SwiftController", referenced from:
      objc-class-ref in com.tuarua.AppleSignInANE.o
ld: symbol(s) not found for architecture arm64
Compilation failed while executing : ld64

**Comment by tuarua** [comment]
Please list the exact AIR version eg AIR 33.1.1.63
There have been 5 releases of 33.1.x.x

**Comment by TanDing** [comment]
I use air sdk 33.1.1.63.

**Comment by TanDing** [comment]
AIR 33.1.1.63
Mac 10.14.6
Xcode 11.3.1
I don't have air sdk 33.0.2.338, so no test.
I'm using Swift ANE for the first time, does air sdk need other settings to use Swift ANE?

**Comment by tuarua** [comment]
It is likely because you are Mojave and not Catalina (10.15)
The ANE is compiled on Catalina because Apple Sign In is latest iOS macOS only.
I am having not seeing any compilation problems
