### ISSUE TITLE
Could not locate iTunesMetadata.plist in archive while installing .ipa to device

### ISSUE THREAD

**Issue by ArtyomTukanow** [tuarua/Apple-Signin-ANE#16]
Hi, I have a problem with AppleSignIn_FW.framework for ios mobile devices.
I have been downloaded the latest version of freSwift (5.0.0) and appleSignInANE (1.6.0). I was moved freswift to AIR and to ios_devendeces. There is no problem while application is package. But when it's installing, the message appears, like:
![image](https://user-images.githubusercontent.com/22097467/99878102-2106e480-2c14-11eb-955e-26ebe2ed0a2b.png)

What am I dooing wrong? XCode v. 12.0, Intellij Idea v. 2019.1.3. AIR v.33.1.1.300

**Comment by tuarua** [comment]
The error underneath: "ApplicationVerificationFailed" is more meaningful. This is usually a signing problem.

Is your p12 or provisioning profile expired?
Have you created a provisioning profile with Apple Sign In entitlements?


![image](https://user-images.githubusercontent.com/12083217/99881887-5a3f5480-2c14-11eb-9c25-ffd261a3affd.png)


I have no problems myself using IJ 2020, AIR33.1.1.300, Xcode 12, iOS 14.2.

**Comment by ArtyomTukanow** [comment]
Thank you for respone. Yes, we are updated our provision profile and it works good without AppleSignInANE. 
But with this ane there are error logs in ios device like:

`copy_parent_certificates Error Domain=NSOSStatusErrorDomain Code=-34018 "Client has neither application-identifier nor keychain-access-groups entitlements" UserInfo={numberOfErrorsDeep=0, NSDescription=Client has neither application-identifier nor keychain-access-groups entitlements}`

`+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:]
: 77: Failed to verify code signature of /var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.qbiLXk/extracted/Payload/GoldenFarm.app/Frameworks/AppleSignInANE_FW.framework : 0xe8008001 (An unknown error has occurred.)`


Just like application-identifier anf keychain-access-groups entitlements are not correct...

**Comment by tuarua** [comment]
What are your entitlements in your app.xml?
You should have this section.
**N.B. XXXXXX is a placeholder**. You need to enter your apple team id

```
<Entitlements><![CDATA[
	<key>com.apple.developer.applesignin</key>
	<array>
		<string>Default</string>
	</array>
	<key>com.apple.developer.team-identifier</key>
	<string>XXXXXX</string>
]]></Entitlements>
```

If I incorrectly leave as XXXXXX I too get a similar error.

> WARNING: could not locate iTunesMetadata.plist in archive!
> WARNING: could not locate Payload/Main.app/SC_Info/Main.sinf in archive!
> ERROR: Install failed. Got error "ApplicationVerificationFailed" with code 0xe8008016: Failed to verify code signature of

**Comment by ArtyomTukanow** [comment]
I recheck com.apple.developer.team-identifier and it's correct. If it was not, it was an error "ApplicationVerificationFailed" anyway. Looks like the com.apple.developer.team-identifier is dublicates anybody other place...

I just finaly wrote ANE on Objective C and it's look like work.
I don't know where is problem, i just resolve it how I can.
